export const serviceGroups = [
  {
    title: "Physiotherapy Services",
    slug: "physiotherapy",
    services: [
      "Musculoskeletal Assessment",
      "Myofascial Trigger Point Release",
      "Pre and Post Operative Rehab",
      "Dry Needling Therapy",
      "Injury Rehabilitation",
      "Posture Correction",
      "Cupping Therapy",
      "Kinesio Taping",
      "Traction",
      "Ultrasound Therapy",
      "Neuro Physiotherapy",
      "Pediatric Physiotherapy",
      "Pre and Postnatal Training",
      "Deep Tissue Massage",
      "Geriatric Physiotherapy",
      "Tailored Exercise Therapy",
      "IFT TENS and Electrical Stimulation",
      "Geriatric Physiotherapy and Home Care",
      "Neck and Back Pain",
      "Muscle and Joint Related Pain"
    ],
  },
  {
    title: "Training Services",
    slug: "training",
    services: [
      "Fitness Training",
      "Corporate Wellness",
      "Strength Training",
      "Sports Specific Training",
      "Sports Training for Children",
      "Physiotherapy at Home",
      "Ergonomic Advice",
      "Psychological Rehab",
      "Womens Wellness",
      "Sports Nutrition",
      "Online Physiotherapy"
    ],
  }
];

export const services = [
  {
    title: "Musculoskeletal Assessment",
    category: "physiotherapy",
    slug: "musculoskeletal-assessment",
    intro: "Understand the cause of pain, stiffness, or movement difficulty with a structured physical assessment.",
    approach: "A focused assessment reviews movement, mobility, strength, posture, and your daily activity needs.",
    benefit: "A clear starting point for a treatment plan tailored to your goals.",
  },
  {
    title: "Myofascial Trigger Point Release",
    category: "physiotherapy",
    slug: "myofascial-trigger-point-release",
    intro: "Target muscle tightness and sensitive trigger points with a guided hands on approach.",
    approach: "Your physiotherapist assesses the affected muscles and selects suitable release techniques based on comfort and clinical need.",
    benefit: "May help reduce muscle tension and support easier movement.",
  },
  {
    title: "Pre and Post Operative Rehab",
    category: "physiotherapy",
    slug: "pre-and-post-operative-rehab",
    intro: "Prepare for surgery or rebuild strength and movement after an operation with guided rehabilitation.",
    approach: "Your plan may include mobility work, progressive exercises, functional training, and recovery education as appropriate.",
    benefit: "Supports a gradual return to everyday activities with professional guidance.",
  },
  {
    title: "Dry Needling Therapy",
    category: "physiotherapy",
    slug: "dry-needling-therapy",
    intro: "A targeted treatment option that may be considered for selected muscle pain conditions.",
    approach: "A qualified clinician first reviews your symptoms and suitability, then explains the procedure and consent process.",
    benefit: "Treatment is selected only when appropriate for your condition and care plan.",
  },
  {
    title: "Injury Rehabilitation",
    category: "physiotherapy",
    slug: "injury-rehabilitation",
    intro: "Work towards a confident return to movement after a sports, work, or everyday injury.",
    approach: "Rehabilitation may progress through pain management, mobility, strength, balance, and activity specific exercises.",
    benefit: "Builds a step by step pathway towards your personal activity goals.",
  },
  {
    title: "Posture Correction",
    category: "physiotherapy",
    slug: "posture-correction",
    intro: "Improve posture awareness and movement habits for daily life, work, and exercise.",
    approach: "Your physiotherapist reviews posture, mobility, strength, and workstation habits before suggesting practical changes.",
    benefit: "Encourages more comfortable movement and sustainable daily habits.",
  },
  {
    title: "Cupping Therapy",
    category: "physiotherapy",
    slug: "cupping-therapy",
    intro: "Explore cupping as an optional part of an individualised physiotherapy plan when suitable.",
    approach: "A clinician reviews your health history and explains expected sensations, possible marks, risks, and alternatives before treatment.",
    benefit: "May be used as one part of a broader care plan when clinically appropriate.",
  },
  {
    title: "Kinesio Taping",
    category: "physiotherapy",
    slug: "kinesio-taping",
    intro: "Learn whether therapeutic taping may support comfort and movement during activity.",
    approach: "Tape placement and tension are selected according to your needs, skin sensitivity, and activity goals.",
    benefit: "Can complement exercise and other rehabilitation strategies.",
  },
  {
    title: "Traction",
    category: "physiotherapy",
    slug: "traction",
    intro: "Explore clinician guided traction when it is appropriate for your symptoms and assessment.",
    approach: "Your physiotherapist checks your condition and explains whether traction is suitable before including it in your plan.",
    benefit: "A treatment option considered as part of a wider rehabilitation approach.",
  },
  {
    title: "Ultrasound Therapy",
    category: "physiotherapy",
    slug: "ultrasound-therapy",
    intro: "Learn whether therapeutic ultrasound is appropriate as part of your physiotherapy care.",
    approach: "Your clinician assesses the affected area and chooses treatments based on your presentation and goals.",
    benefit: "May complement other treatment methods when appropriate.",
  },
  {
    title: "Neuro Physiotherapy",
    category: "physiotherapy",
    slug: "neuro-physiotherapy",
    intro: "Support movement, balance, coordination, and daily function after neurological conditions.",
    approach: "Sessions are adapted to individual ability and may include movement practice, balance work, transfers, and functional tasks.",
    benefit: "Focuses on meaningful activities and individual rehabilitation goals.",
  },
  {
    title: "Pediatric Physiotherapy",
    category: "physiotherapy",
    slug: "pediatric-physiotherapy",
    intro: "Movement support for children through age appropriate and engaging activities.",
    approach: "The therapist considers developmental needs, movement skills, family priorities, and the child’s comfort.",
    benefit: "Encourages participation in everyday play and age appropriate activities.",
  },
  {
    title: "Pre and Postnatal Training",
    category: "physiotherapy",
    slug: "pre-and-postnatal-training",
    intro: "Movement and exercise guidance during pregnancy and after childbirth, tailored to individual needs.",
    approach: "A clinician considers stage of pregnancy or recovery, symptoms, medical advice, and current fitness before planning activity.",
    benefit: "Supports a gradual and comfortable return to movement.",
  },
  {
    title: "Deep Tissue Massage",
    category: "physiotherapy",
    slug: "deep-tissue-massage",
    intro: "A hands on option that may help address muscle tightness as part of a wider care plan.",
    approach: "The therapist checks the area, pressure preference, and suitability before choosing an approach.",
    benefit: "May support short term relaxation and comfort for some people.",
  },
  {
    title: "Geriatric Physiotherapy",
    category: "physiotherapy",
    slug: "geriatric-physiotherapy",
    intro: "Movement and strength support designed around the needs and goals of older adults.",
    approach: "Care may include balance practice, strength exercises, mobility work, and strategies for everyday tasks.",
    benefit: "Aims to support safe movement, confidence, and independence.",
  },
  {
    title: "Tailored Exercise Therapy",
    category: "physiotherapy",
    slug: "tailored-exercise-therapy",
    intro: "A personalised exercise plan shaped around your ability, symptoms, and goals.",
    approach: "Your physiotherapist selects and progresses mobility, strength, balance, or functional exercises based on your response.",
    benefit: "Helps make rehabilitation more structured and goal focused.",
  },
  {
    title: "IFT TENS and Electrical Stimulation",
    category: "physiotherapy",
    slug: "ift-tens-and-electrical-stimulation",
    intro: "Explore electrical stimulation options when they are appropriate for your presentation.",
    approach: "Your clinician checks suitability, explains the selected modality, and considers your comfort and safety before use.",
    benefit: "May be used alongside other treatments as part of an individual plan.",
  },
  {
    title: "Geriatric Physiotherapy and Home Care",
    category: "physiotherapy",
    slug: "geriatric-physiotherapy-and-home-care",
    intro: "Physiotherapy support for older adults in a familiar home environment when available.",
    approach: "Care can focus on mobility, strength, balance, safe transfers, and practical daily activities.",
    benefit: "Helps connect rehabilitation goals with the home environment.",
  },
  {
    title: "Neck and Back Pain",
    category: "physiotherapy",
    slug: "neck-and-back-pain",
    intro: "Get guidance for neck or back discomfort with a plan based on assessment and your daily needs.",
    approach: "Care may include education, graded movement, mobility work, strength exercises, and practical activity advice.",
    benefit: "Supports improved function and confidence with movement.",
  },
  {
    title: "Muscle and Joint Related Pain",
    category: "physiotherapy",
    slug: "muscle-and-joint-related-pain",
    intro: "Assessment and rehabilitation for muscle or joint discomfort affecting everyday activity.",
    approach: "Your plan is based on symptoms, movement, strength, relevant history, and goals agreed with your clinician.",
    benefit: "Aims to improve function through suitable treatment and exercise.",
  },
  {
    title: "Fitness Training",
    category: "training",
    slug: "fitness-training",
    intro: "Build a practical fitness routine that reflects your current level and goals.",
    approach: "Training can combine movement preparation, strength, endurance, and progress checks based on your needs.",
    benefit: "Supports consistent training habits and measurable personal goals.",
  },
  {
    title: "Corporate Wellness",
    category: "training",
    slug: "corporate-wellness",
    intro: "Support healthier movement habits and wellbeing in the workplace.",
    approach: "Programmes can include movement breaks, posture education, mobility sessions, and practical workplace guidance.",
    benefit: "Helps teams build healthier everyday routines.",
  },
  {
    title: "Strength Training",
    category: "training",
    slug: "strength-training",
    intro: "Develop strength through a progressive programme matched to your experience and ability.",
    approach: "Sessions can include technique coaching, suitable resistance exercises, recovery guidance, and progression checks.",
    benefit: "Builds a structured approach to strength and functional capacity.",
  },
  {
    title: "Sports Specific Training",
    category: "training",
    slug: "sports-specific-training",
    intro: "Prepare for the physical demands of your chosen sport with focused training.",
    approach: "Training can address movement patterns, strength, agility, balance, and conditioning relevant to your sport.",
    benefit: "Helps align training with sport specific performance goals.",
  },
  {
    title: "Sports Training for Children",
    category: "training",
    slug: "sports-training-for-children",
    intro: "Age appropriate sports movement and fitness sessions for children.",
    approach: "Activities are planned around the child’s age, skill level, enjoyment, movement quality, and safe progression.",
    benefit: "Encourages confidence, coordination, and positive activity habits.",
  },
  {
    title: "Physiotherapy at Home",
    category: "training",
    slug: "physiotherapy-at-home",
    intro: "Explore physiotherapy support in your home environment, subject to service availability.",
    approach: "A physiotherapist can assess your needs and plan suitable exercises or functional practice for your space.",
    benefit: "Makes it easier to connect rehabilitation with everyday activities at home.",
  },
  {
    title: "Ergonomic Advice",
    category: "training",
    slug: "ergonomic-advice",
    intro: "Make your workspace and daily setup more comfortable and practical.",
    approach: "Advice may cover workstation arrangement, sitting habits, movement breaks, and task specific adjustments.",
    benefit: "Supports better movement habits throughout the workday.",
  },
  {
    title: "Psychological Rehab",
    category: "training",
    slug: "psychological-rehab",
    intro: "Explore supportive rehabilitation approaches that consider confidence, motivation, and adjustment during recovery.",
    approach: "Your care team can discuss suitable support and referral options based on your needs and the service available.",
    benefit: "Recognises that recovery can involve both physical and emotional challenges.",
  },
  {
    title: "Womens Wellness",
    category: "training",
    slug: "womens-wellness",
    intro: "Movement and wellbeing support shaped around individual women’s health goals.",
    approach: "Your plan is discussed privately and adapted to your needs, activity level, and relevant clinical guidance.",
    benefit: "Offers a supportive, individualised approach to movement and wellbeing.",
  },
  {
    title: "Sports Nutrition",
    category: "training",
    slug: "sports-nutrition",
    intro: "Build practical nutrition habits that support training and recovery goals.",
    approach: "Guidance can cover general fuelling habits and recovery routines. Individual medical nutrition needs should be discussed with a qualified professional.",
    benefit: "Supports informed habits alongside a balanced training plan.",
  },
  {
    title: "Online Physiotherapy",
    category: "training",
    slug: "online-physiotherapy",
    intro: "Access guided physiotherapy consultations remotely when suitable for your needs.",
    approach: "A clinician discusses your concerns, observes movement where possible, and suggests an appropriate plan or in person assessment if needed.",
    benefit: "Offers a convenient option for selected concerns and follow up support.",
  }
];

export const getServiceBySlug = (slug) => services.find((service) => service.slug === slug);
